

# RTC SDK
pod 'BytePlusRTC', '3.52.118', :source => 'https://github.com/byteplus-sdk/byteplus-specs.git'

target 'RTCSolution' do
  platform :ios, '12.0'
  
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # Basic Component
  pod 'ToolKit', :path => '../RTCSolution/APP/ToolKit'
  
  # Scene source code
  # Login Kit
  pod 'BytePlusLoginKit', :path => '../RTCSolution/APP/BytePlusLoginKit'

  # Get RTS Params Kit
  pod 'JoinRTSParamsKit', :path => '../RTCSolution/APP/JoinRTSParamsKit'

  # Live Share Demo
  pod 'LiveShareDemo', :path => '../RTCSolution/APP/LiveShareDemo'
  pod 'TTSDK/LivePull', '1.36.200.1-premium', :source => 'https://github.com/volcengine/volcengine-specs.git'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        
      end
    end
  end
end
